import type { Metadata } from "next"

import { ColorSchemeScript, MantineProvider } from "@mantine/core"
import { theme } from "@rss3/mantine-theme"

import Providers from "./providers"

import "./globals.css"

// font
import { Poppins } from "next/font/google"

const font = Poppins({
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  subsets: ["latin"],
  variable: "--font-poppins",
})
theme.fontFamily = font.style.fontFamily

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ColorSchemeScript />
        <Providers>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </Providers>
      </body>
    </html>
  )
}
